export const languages = [
  {id: 1, code: "aar", name: "Afar" },
  {id: 2, code: "abk", name: "Abkhazian" },
  {id: 3, code: "ace", name: "Achinese" },
  {id: 4, code: "ach", name: "Acoli" },
  {id: 5, code: "ada", name: "Adangme" },
  {id: 6, code: "ady", name: "Adyghe; Adygei" },
  {id: 7, code: "afa", name: "Afro-Asiatic languages" },
  {id: 8, code: "afh", name: "Afrihili" },
  {id: 9, code: "afr", name: "Afrikaans" },
  {id: 10, code: "ain", name: "Ainu" },
  {id: 11, code: "aka", name: "Akan" },
  {id: 12, code: "akk", name: "Akkadian" },
  {id: 13, code: "alb", name: "Albanian" },
  {id: 14, code: "sqi", name: "Albanian" },
  {id: 15, code: "ale", name: "Aleut" },
  {id: 16, code: "alg", name: "Algonquian languages" },
  {id: 17, code: "alt", name: "Southern Altai" },
  {id: 18, code: "amh", name: "Amharic" },
  {id: 19, code: "ang", name: "English, Old (ca.450-1100)" },
  {id: 20, code: "anp", name: "Angika" },
  {id: 21, code: "apa", name: "Apache languages" },
  {id: 22, code: "ara", name: "Arabic" },
  {id: 23, code: "arc", name: "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)" },
  {id: 24, code: "arg", name: "Aragonese" },
  {id: 25, code: "arm", name: "Armenian" },
  {id: 26, code: "hye", name: "Armenian" },
  {id: 27, code: "arn", name: "Mapudungun; Mapuche" },
  {id: 28, code: "arp", name: "Arapaho" },
  {id: 29, code: "art", name: "Artificial languages" },
  {id: 30, code: "arw", name: "Arawak" },
  {id: 31, code: "asm", name: "Assamese" },
  {id: 32, code: "ast", name: "Asturian; Bable; Leonese; Asturleonese" },
  {id: 33, code: "ath", name: "Athapascan languages" },
  {id: 34, code: "aus", name: "Australian languages" },
  {id: 35, code: "ava", name: "Avaric" },
  {id: 36, code: "ave", name: "Avestan" },
  {id: 37, code: "awa", name: "Awadhi" },
  {id: 38, code: "aym", name: "Aymara" },
  {id: 39, code: "aze", name: "Azerbaijani" },
  {id: 40, code: "bad", name: "Banda languages" },
  {id: 41, code: "bai", name: "Bamileke languages" },
  {id: 42, code: "bak", name: "Bashkir" },
  {id: 43, code: "bal", name: "Baluchi" },
  {id: 44, code: "bam", name: "Bambara" },
  {id: 45, code: "ban", name: "Balinese" },
  {id: 46, code: "baq", name: "Basque" },
  {id: 47, code: "eus", name: "Basque" },
  {id: 48, code: "bas", name: "Basa" },
  {id: 49, code: "bat", name: "Baltic languages" },
  {id: 50, code: "bej", name: "Beja; Bedawiyet" },
  {id: 51, code: "bel", name: "Belarusian" },
  {id: 52, code: "bem", name: "Bemba" },
  {id: 53, code: "ben", name: "Bengali" },
  {id: 54, code: "ber", name: "Berber languages" },
  {id: 55, code: "bho", name: "Bhojpuri" },
  {id: 56, code: "bih", name: "Bihari languages" },
  {id: 57, code: "bik", name: "Bikol" },
  {id: 58, code: "bin", name: "Bini; Edo" },
  {id: 59, code: "bis", name: "Bislama" },
  {id: 60, code: "bla", name: "Siksika" },
  {id: 61, code: "bnt", name: "Bantu (Other)" },
  {id: 62, code: "bos", name: "Bosnian" },
  {id: 63, code: "bra", name: "Braj" },
  {id: 64, code: "bre", name: "Breton" },
  {id: 65, code: "btk", name: "Batak languages" },
  {id: 66, code: "bua", name: "Buriat" },
  {id: 67, code: "bug", name: "Buginese" },
  {id: 68, code: "bul", name: "Bulgarian" },
  {id: 69, code: "bur", name: "Burmese" },
  {id: 70, code: "mya", name: "Burmese" },
  {id: 71, code: "byn", name: "Blin; Bilin" },
  {id: 72, code: "cad", name: "Caddo" },
  {id: 73, code: "cai", name: "Central American Indian languages" },
  {id: 74, code: "car", name: "Galibi Carib" },
  {id: 75, code: "cat", name: "Catalan; Valencian" },
  {id: 76, code: "cau", name: "Caucasian languages" },
  {id: 77, code: "ceb", name: "Cebuano" },
  {id: 78, code: "cel", name: "Celtic languages" },
  {id: 79, code: "cha", name: "Chamorro" },
  {id: 80, code: "chb", name: "Chibcha" },
  {id: 81, code: "che", name: "Chechen" },
  {id: 82, code: "chg", name: "Chagatai" },
  {id: 83, code: "chi", name: "Chinese" },
  {id: 84, code: "zho", name: "Chinese" },
  {id: 85, code: "chk", name: "Chuukese" },
  {id: 86, code: "chm", name: "Mari" },
  {id: 87, code: "chn", name: "Chinook jargon" },
  {id: 88, code: "cho", name: "Choctaw" },
  {id: 89, code: "chp", name: "Chipewyan; Dene Suline" },
  {id: 90, code: "chr", name: "Cherokee" },
  {id: 91, code: "chu", name: "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" },
  {id: 92, code: "chv", name: "Chuvash" },
  {id: 93, code: "chy", name: "Cheyenne" },
  {id: 94, code: "cmc", name: "Chamic languages" },
  {id: 95, code: "cop", name: "Coptic" },
  {id: 96, code: "cor", name: "Cornish" },
  {id: 97, code: "cos", name: "Corsican" },
  {id: 98, code: "cpe", name: "Creoles and pidgins, English based" },
  {id: 99, code: "cpf", name: "Creoles and pidgins, French-based " },
  {id: 100, code: "cpp", name: "Creoles and pidgins, Portuguese-based " },
  {id: 101, code: "cre", name: "Cree" },
  {id: 102, code: "crh", name: "Crimean Tatar; Crimean Turkish" },
  {id: 103, code: "crp", name: "Creoles and pidgins " },
  {id: 104, code: "csb", name: "Kashubian" },
  {id: 105, code: "cus", name: "Cushitic languages" },
  {id: 106, code: "cze", name: "Czech" },
  {id: 107, code: "ces", name: "Czech" },
  {id: 108, code: "dak", name: "Dakota" },
  {id: 109, code: "dan", name: "Danish" },
  {id: 110, code: "dar", name: "Dargwa" },
  {id: 111, code: "day", name: "Land Dayak languages" },
  {id: 112, code: "del", name: "Delaware" },
  {id: 113, code: "den", name: "Slave (Athapascan)" },
  {id: 114, code: "dgr", name: "Dogrib" },
  {id: 115, code: "din", name: "Dinka" },
  {id: 116, code: "div", name: "Divehi; Dhivehi; Maldivian" },
  {id: 117, code: "doi", name: "Dogri" },
  {id: 118, code: "dra", name: "Dravidian languages" },
  {id: 119, code: "dsb", name: "Lower Sorbian" },
  {id: 120, code: "dua", name: "Duala" },
  {id: 121, code: "dum", name: "Dutch, Middle (ca.1050-1350)" },
  {id: 122, code: "dut", name: "Dutch; Flemish" },
  {id: 123, code: "nld", name: "Dutch; Flemish" },
  {id: 124, code: "dyu", name: "Dyula" },
  {id: 125, code: "dzo", name: "Dzongkha" },
  {id: 126, code: "efi", name: "Efik" },
  {id: 127, code: "egy", name: "Egyptian (Ancient)" },
  {id: 128, code: "eka", name: "Ekajuk" },
  {id: 129, code: "elx", name: "Elamite" },
  {id: 130, code: "eng", name: "English" },
  {id: 131, code: "enm", name: "English, Middle (1100-1500)" },
  {id: 132, code: "epo", name: "Esperanto" },
  {id: 133, code: "est", name: "Estonian" },
  {id: 134, code: "ewe", name: "Ewe" },
  {id: 135, code: "ewo", name: "Ewondo" },
  {id: 136, code: "fan", name: "Fang" },
  {id: 137, code: "fao", name: "Faroese" },
  {id: 138, code: "fat", name: "Fanti" },
  {id: 139, code: "fij", name: "Fijian" },
  {id: 140, code: "fil", name: "Filipino; Pilipino" },
  {id: 141, code: "fin", name: "Finnish" },
  {id: 142, code: "fiu", name: "Finno-Ugrian languages" },
  {id: 143, code: "fon", name: "Fon" },
  {id: 144, code: "fre", name: "French" },
  {id: 145, code: "fra", name: "French" },
  {id: 146, code: "frm", name: "French, Middle (ca.1400-1600)" },
  {id: 147, code: "fro", name: "French, Old (842-ca.1400)" },
  {id: 148, code: "frr", name: "Northern Frisian" },
  {id: 149, code: "frs", name: "Eastern Frisian" },
  {id: 150, code: "fry", name: "Western Frisian" },
  {id: 151, code: "ful", name: "Fulah" },
  {id: 152, code: "fur", name: "Friulian" },
  {id: 153, code: "gaa", name: "Ga" },
  {id: 154, code: "gay", name: "Gayo" },
  {id: 155, code: "gba", name: "Gbaya" },
  {id: 156, code: "gem", name: "Germanic languages" },
  {id: 157, code: "geo", name: "Georgian" },
  {id: 158, code: "kat", name: "Georgian" },
  {id: 159, code: "ger", name: "German" },
  {id: 160, code: "deu", name: "German" },
  {id: 161, code: "gez", name: "Geez" },
  {id: 162, code: "gil", name: "Gilbertese" },
  {id: 163, code: "gla", name: "Gaelic; Scottish Gaelic" },
  {id: 164, code: "gle", name: "Irish" },
  {id: 165, code: "glg", name: "Galician" },
  {id: 166, code: "glv", name: "Manx" },
  {id: 167, code: "gmh", name: "German, Middle High (ca.1050-1500)" },
  {id: 168, code: "goh", name: "German, Old High (ca.750-1050)" },
  {id: 169, code: "gon", name: "Gondi" },
  {id: 170, code: "gor", name: "Gorontalo" },
  {id: 171, code: "got", name: "Gothic" },
  {id: 172, code: "grb", name: "Grebo" },
  {id: 173, code: "grc", name: "Greek, Ancient (to 1453)" },
  {id: 174, code: "gre", name: "Greek, Modern (1453-)" },
  {id: 175, code: "ell", name: "Greek, Modern (1453-)" },
  {id: 176, code: "grn", name: "Guarani" },
  {id: 177, code: "gsw", name: "Swiss German; Alemannic; Alsatian" },
  {id: 178, code: "guj", name: "Gujarati" },
  {id: 179, code: "gwi", name: "Gwich'in" },
  {id: 180, code: "hai", name: "Haida" },
  {id: 181, code: "hat", name: "Haitian; Haitian Creole" },
  {id: 182, code: "hau", name: "Hausa" },
  {id: 183, code: "haw", name: "Hawaiian" },
  {id: 184, code: "heb", name: "Hebrew" },
  {id: 185, code: "her", name: "Herero" },
  {id: 186, code: "hil", name: "Hiligaynon" },
  {id: 187, code: "him", name: "Himachali languages; Western Pahari languages" },
  {id: 188, code: "hin", name: "Hindi" },
  {id: 189, code: "hit", name: "Hittite" },
  {id: 190, code: "hmn", name: "Hmong; Mong" },
  {id: 191, code: "hmo", name: "Hiri Motu" },
  {id: 192, code: "hrv", name: "Croatian" },
  {id: 193, code: "hsb", name: "Upper Sorbian" },
  {id: 194, code: "hun", name: "Hungarian" },
  {id: 195, code: "hup", name: "Hupa" },
  {id: 196, code: "iba", name: "Iban" },
  {id: 197, code: "ibo", name: "Igbo" },
  {id: 198, code: "ice", name: "Icelandic" },
  {id: 199, code: "isl", name: "Icelandic" },
  {id: 200, code: "ido", name: "Ido" },
  {id: 201, code: "iii", name: "Sichuan Yi; Nuosu" },
  {id: 202, code: "ijo", name: "Ijo languages" },
  {id: 203, code: "iku", name: "Inuktitut" },
  {id: 204, code: "ile", name: "Interlingue; Occidental" },
  {id: 205, code: "ilo", name: "Iloko" },
  {id: 206, code: "ina", name: "Interlingua (International Auxiliary Language Association)" },
  {id: 207, code: "inc", name: "Indic languages" },
  {id: 208, code: "ind", name: "Indonesian" },
  {id: 209, code: "ine", name: "Indo-European languages" },
  {id: 210, code: "inh", name: "Ingush" },
  {id: 211, code: "ipk", name: "Inupiaq" },
  {id: 212, code: "ira", name: "Iranian languages" },
  {id: 213, code: "iro", name: "Iroquoian languages" },
  {id: 214, code: "ita", name: "Italian" },
  {id: 215, code: "jav", name: "Javanese" },
  {id: 216, code: "jbo", name: "Lojban" },
  {id: 217, code: "jpn", name: "Japanese" },
  {id: 218, code: "jpr", name: "Judeo-Persian" },
  {id: 219, code: "jrb", name: "Judeo-Arabic" },
  {id: 220, code: "kaa", name: "Kara-Kalpak" },
  {id: 221, code: "kab", name: "Kabyle" },
  {id: 222, code: "kac", name: "Kachin; Jingpho" },
  {id: 223, code: "kal", name: "Kalaallisut; Greenlandic" },
  {id: 224, code: "kam", name: "Kamba" },
  {id: 225, code: "kan", name: "Kannada" },
  {id: 226, code: "kar", name: "Karen languages" },
  {id: 227, code: "kas", name: "Kashmiri" },
  {id: 228, code: "kau", name: "Kanuri" },
  {id: 229, code: "kaw", name: "Kawi" },
  {id: 230, code: "kaz", name: "Kazakh" },
  {id: 231, code: "kbd", name: "Kabardian" },
  {id: 232, code: "kha", name: "Khasi" },
  {id: 233, code: "khi", name: "Khoisan languages" },
  {id: 234, code: "khm", name: "Central Khmer" },
  {id: 235, code: "kho", name: "Khotanese; Sakan" },
  {id: 236, code: "kik", name: "Kikuyu; Gikuyu" },
  {id: 237, code: "kin", name: "Kinyarwanda" },
  {id: 238, code: "kir", name: "Kirghiz; Kyrgyz" },
  {id: 239, code: "kmb", name: "Kimbundu" },
  {id: 240, code: "kok", name: "Konkani" },
  {id: 241, code: "kom", name: "Komi" },
  {id: 242, code: "kon", name: "Kongo" },
  {id: 243, code: "kor", name: "Korean" },
  {id: 244, code: "kos", name: "Kosraean" },
  {id: 245, code: "kpe", name: "Kpelle" },
  {id: 246, code: "krc", name: "Karachay-Balkar" },
  {id: 247, code: "krl", name: "Karelian" },
  {id: 248, code: "kro", name: "Kru languages" },
  {id: 249, code: "kru", name: "Kurukh" },
  {id: 250, code: "kua", name: "Kuanyama; Kwanyama" },
  {id: 251, code: "kum", name: "Kumyk" },
  {id: 252, code: "kur", name: "Kurdish" },
  {id: 253, code: "kut", name: "Kutenai" },
  {id: 254, code: "lad", name: "Ladino" },
  {id: 255, code: "lah", name: "Lahnda" },
  {id: 256, code: "lam", name: "Lamba" },
  {id: 257, code: "lao", name: "Lao" },
  {id: 258, code: "lat", name: "Latin" },
  {id: 259, code: "lav", name: "Latvian" },
  {id: 260, code: "lez", name: "Lezghian" },
  {id: 261, code: "lim", name: "Limburgan; Limburger; Limburgish" },
  {id: 262, code: "lin", name: "Lingala" },
  {id: 263, code: "lit", name: "Lithuanian" },
  {id: 264, code: "lol", name: "Mongo" },
  {id: 265, code: "loz", name: "Lozi" },
  {id: 266, code: "ltz", name: "Luxembourgish; Letzeburgesch" },
  {id: 267, code: "lua", name: "Luba-Lulua" },
  {id: 268, code: "lub", name: "Luba-Katanga" },
  {id: 269, code: "lug", name: "Ganda" },
  {id: 270, code: "lui", name: "Luiseno" },
  {id: 271, code: "lun", name: "Lunda" },
  {id: 272, code: "luo", name: "Luo (Kenya and Tanzania)" },
  {id: 273, code: "lus", name: "Lushai" },
  {id: 274, code: "mac", name: "Macedonian" },
  {id: 275, code: "mkd", name: "Macedonian" },
  {id: 276, code: "mad", name: "Madurese" },
  {id: 277, code: "mag", name: "Magahi" },
  {id: 278, code: "mah", name: "Marshallese" },
  {id: 279, code: "mai", name: "Maithili" },
  {id: 280, code: "mak", name: "Makasar" },
  {id: 281, code: "mal", name: "Malayalam" },
  {id: 282, code: "man", name: "Mandingo" },
  {id: 283, code: "mao", name: "Maori" },
  {id: 284, code: "mri", name: "Maori" },
  {id: 285, code: "map", name: "Austronesian languages" },
  {id: 286, code: "mar", name: "Marathi" },
  {id: 287, code: "mas", name: "Masai" },
  {id: 288, code: "may", name: "Malay" },
  {id: 289, code: "msa", name: "Malay" },
  {id: 290, code: "mdf", name: "Moksha" },
  {id: 291, code: "mdr", name: "Mandar" },
  {id: 292, code: "men", name: "Mende" },
  {id: 293, code: "mga", name: "Irish, Middle (900-1200)" },
  {id: 294, code: "mic", name: "Mi'kmaq; Micmac" },
  {id: 295, code: "min", name: "Minangkabau" },
  {id: 296, code: "mis", name: "Uncoded languages" },
  {id: 297, code: "mkh", name: "Mon-Khmer languages" },
  {id: 298, code: "mlg", name: "Malagasy" },
  {id: 299, code: "mlt", name: "Maltese" },
  {id: 300, code: "mnc", name: "Manchu" },
  {id: 301, code: "mni", name: "Manipuri" },
  {id: 302, code: "mno", name: "Manobo languages" },
  {id: 303, code: "moh", name: "Mohawk" },
  {id: 304, code: "mon", name: "Mongolian" },
  {id: 305, code: "mos", name: "Mossi" },
  {id: 306, code: "mul", name: "Multiple languages" },
  {id: 307, code: "mun", name: "Munda languages" },
  {id: 308, code: "mus", name: "Creek" },
  {id: 309, code: "mwl", name: "Mirandese" },
  {id: 310, code: "mwr", name: "Marwari" },
  {id: 311, code: "myn", name: "Mayan languages" },
  {id: 312, code: "myv", name: "Erzya" },
  {id: 313, code: "nah", name: "Nahuatl languages" },
  {id: 314, code: "nai", name: "North American Indian languages" },
  {id: 315, code: "nap", name: "Neapolitan" },
  {id: 316, code: "nau", name: "Nauru" },
  {id: 317, code: "nav", name: "Navajo; Navaho" },
  {id: 318, code: "nbl", name: "Ndebele, South; South Ndebele" },
  {id: 319, code: "nde", name: "Ndebele, North; North Ndebele" },
  {id: 320, code: "ndo", name: "Ndonga" },
  {id: 321, code: "nds", name: "Low German; Low Saxon; German, Low; Saxon, Low" },
  {id: 322, code: "nep", name: "Nepali" },
  {id: 323, code: "new", name: "Nepal Bhasa; Newari" },
  {id: 324, code: "nia", name: "Nias" },
  {id: 325, code: "nic", name: "Niger-Kordofanian languages" },
  {id: 326, code: "niu", name: "Niuean" },
  {id: 327, code: "nno", name: "Norwegian Nynorsk; Nynorsk, Norwegian" },
  {id: 328, code: "nob", name: "Bokmål, Norwegian; Norwegian Bokmål" },
  {id: 329, code: "nog", name: "Nogai" },
  {id: 330, code: "non", name: "Norse, Old" },
  {id: 331, code: "nor", name: "Norwegian" },
  {id: 332, code: "nqo", name: "N'Ko" },
  {id: 333, code: "nso", name: "Pedi; Sepedi; Northern Sotho" },
  {id: 334, code: "nub", name: "Nubian languages" },
  {id: 335, code: "nwc", name: "Classical Newari; Old Newari; Classical Nepal Bhasa" },
  {id: 336, code: "nya", name: "Chichewa; Chewa; Nyanja" },
  {id: 337, code: "nym", name: "Nyamwezi" },
  {id: 338, code: "nyn", name: "Nyankole" },
  {id: 339, code: "nyo", name: "Nyoro" },
  {id: 340, code: "nzi", name: "Nzima" },
  {id: 341, code: "oci", name: "Occitan (post 1500); Provençal" },
  {id: 342, code: "oji", name: "Ojibwa" },
  {id: 343, code: "ori", name: "Oriya" },
  {id: 344, code: "orm", name: "Oromo" },
  {id: 345, code: "osa", name: "Osage" },
  {id: 346, code: "oss", name: "Ossetian; Ossetic" },
  {id: 347, code: "ota", name: "Turkish, Ottoman (1500-1928)" },
  {id: 348, code: "oto", name: "Otomian languages" },
  {id: 349, code: "paa", name: "Papuan languages" },
  {id: 350, code: "pag", name: "Pangasinan" },
  {id: 351, code: "pal", name: "Pahlavi" },
  {id: 352, code: "pam", name: "Pampanga; Kapampangan" },
  {id: 353, code: "pan", name: "Panjabi; Punjabi" },
  {id: 354, code: "pap", name: "Papiamento" },
  {id: 355, code: "pau", name: "Palauan" },
  {id: 356, code: "peo", name: "Persian, Old (ca.600-400 B.C.)" },
  {id: 357, code: "per", name: "Persian" },
  {id: 358, code: "fas", name: "Persian" },
  {id: 359, code: "phi", name: "Philippine languages" },
  {id: 360, code: "phn", name: "Phoenician" },
  {id: 361, code: "pli", name: "Pali" },
  {id: 362, code: "pol", name: "Polish" },
  {id: 363, code: "pon", name: "Pohnpeian" },
  {id: 364, code: "por", name: "Portuguese" },
  {id: 365, code: "pra", name: "Prakrit languages" },
  {id: 366, code: "pro", name: "Provençal, Old (to 1500)" },
  {id: 367, code: "pus", name: "Pushto; Pashto" },
  {id: 368, code: "qaa-qtz", code: "Reserved for local use"},
  {id: 369, code: "que", name: "Quechua" },
  {id: 370, code: "raj", name: "Rajasthani" },
  {id: 371, code: "rap", name: "Rapanui" },
  {id: 372, code: "rar", name: "Rarotongan; Cook Islands Maori" },
  {id: 373, code: "roa", name: "Romance languages" },
  {id: 374, code: "roh", name: "Romansh" },
  {id: 375, code: "rom", name: "Romany" },
  {id: 376, code: "rum", name: "Romanian; Moldavian; Moldovan" },
  {id: 377, code: "ron", name: "Romanian; Moldavian; Moldovan" },
  {id: 378, code: "run", name: "Rundi" },
  {id: 379, code: "rup", name: "Aromanian; Arumanian; Macedo-Romanian" },
  {id: 380, code: "rus", name: "Russian" },
  {id: 381, code: "sad", name: "Sandawe" },
  {id: 382, code: "sag", name: "Sango" },
  {id: 383, code: "sah", name: "Yakut" },
  {id: 384, code: "sai", name: "South American Indian (Other)" },
  {id: 385, code: "sal", name: "Salishan languages" },
  {id: 386, code: "sam", name: "Samaritan Aramaic" },
  {id: 387, code: "san", name: "Sanskrit" },
  {id: 388, code: "sas", name: "Sasak" },
  {id: 389, code: "sat", name: "Santali" },
  {id: 390, code: "scn", name: "Sicilian" },
  {id: 391, code: "sco", name: "Scots" },
  {id: 392, code: "sel", name: "Selkup" },
  {id: 393, code: "sem", name: "Semitic languages" },
  {id: 394, code: "sga", name: "Irish, Old (to 900)" },
  {id: 395, code: "sgn", name: "Sign Languages" },
  {id: 396, code: "shn", name: "Shan" },
  {id: 397, code: "sid", name: "Sidamo" },
  {id: 398, code: "sin", name: "Sinhala; Sinhalese" },
  {id: 399, code: "sio", name: "Siouan languages" },
  {id: 400, code: "sit", name: "Sino-Tibetan languages" },
  {id: 401, code: "sla", name: "Slavic languages" },
  {id: 402, code: "slo", name: "Slovak" },
  {id: 403, code: "slk", name: "Slovak" },
  {id: 404, code: "slv", name: "Slovenian" },
  {id: 405, code: "sma", name: "Southern Sami" },
  {id: 406, code: "sme", name: "Northern Sami" },
  {id: 407, code: "smi", name: "Sami languages" },
  {id: 408, code: "smj", name: "Lule Sami" },
  {id: 409, code: "smn", name: "Inari Sami" },
  {id: 410, code: "smo", name: "Samoan" },
  {id: 411, code: "sms", name: "Skolt Sami" },
  {id: 412, code: "sna", name: "Shona" },
  {id: 413, code: "snd", name: "Sindhi" },
  {id: 414, code: "snk", name: "Soninke" },
  {id: 415, code: "sog", name: "Sogdian" },
  {id: 416, code: "som", name: "Somali" },
  {id: 417, code: "son", name: "Songhai languages" },
  {id: 418, code: "sot", name: "Sotho, Southern" },
  {id: 419, code: "spa", name: "Spanish; Castilian" },
  {id: 420, code: "srd", name: "Sardinian" },
  {id: 421, code: "srn", name: "Sranan Tongo" },
  {id: 422, code: "srp", name: "Serbian" },
  {id: 423, code: "srr", name: "Serer" },
  {id: 424, code: "ssa", name: "Nilo-Saharan languages" },
  {id: 425, code: "ssw", name: "Swati" },
  {id: 426, code: "suk", name: "Sukuma" },
  {id: 427, code: "sun", name: "Sundanese" },
  {id: 428, code: "sus", name: "Susu" },
  {id: 429, code: "sux", name: "Sumerian" },
  {id: 430, code: "swa", name: "Swahili" },
  {id: 431, code: "swe", name: "Swedish" },
  {id: 432, code: "syc", name: "Classical Syriac" },
  {id: 433, code: "syr", name: "Syriac" },
  {id: 434, code: "tah", name: "Tahitian" },
  {id: 435, code: "tai", name: "Tai languages" },
  {id: 436, code: "tam", name: "Tamil" },
  {id: 437, code: "tat", name: "Tatar" },
  {id: 438, code: "tel", name: "Telugu" },
  {id: 439, code: "tem", name: "Timne" },
  {id: 440, code: "ter", name: "Tereno" },
  {id: 441, code: "tet", name: "Tetum" },
  {id: 442, code: "tgk", name: "Tajik" },
  {id: 443, code: "tgl", name: "Tagalog" },
  {id: 444, code: "tha", name: "Thai" },
  {id: 445, code: "tib", name: "Tibetan" },
  {id: 446, code: "bod", name: "Tibetan" },
  {id: 447, code: "tig", name: "Tigre" },
  {id: 448, code: "tir", name: "Tigrinya" },
  {id: 449, code: "tiv", name: "Tiv" },
  {id: 450, code: "tkl", name: "Tokelau" },
  {id: 451, code: "tlh", name: "Klingon; tlhIngan-Hol" },
  {id: 452, code: "tli", name: "Tlingit" },
  {id: 453, code: "tmh", name: "Tamashek" },
  {id: 454, code: "tog", name: "Tonga (Nyasa)" },
  {id: 455, code: "ton", name: "Tonga (Tonga Islands)" },
  {id: 456, code: "tpi", name: "Tok Pisin" },
  {id: 457, code: "tsi", name: "Tsimshian" },
  {id: 458, code: "tsn", name: "Tswana" },
  {id: 459, code: "tso", name: "Tsonga" },
  {id: 460, code: "tuk", name: "Turkmen" },
  {id: 461, code: "tum", name: "Tumbuka" },
  {id: 462, code: "tup", name: "Tupi languages" },
  {id: 463, code: "tur", name: "Turkish" },
  {id: 464, code: "tut", name: "Altaic languages" },
  {id: 465, code: "tvl", name: "Tuvalu" },
  {id: 466, code: "twi", name: "Twi" },
  {id: 467, code: "tyv", name: "Tuvinian" },
  {id: 468, code: "udm", name: "Udmurt" },
  {id: 469, code: "uga", name: "Ugaritic" },
  {id: 470, code: "uig", name: "Uighur; Uyghur" },
  {id: 471, code: "ukr", name: "Ukrainian" },
  {id: 472, code: "umb", name: "Umbundu" },
  {id: 473, code: "und", name: "Undetermined" },
  {id: 474, code: "urd", name: "Urdu" },
  {id: 475, code: "uzb", name: "Uzbek" },
  {id: 476, code: "vai", name: "Vai" },
  {id: 477, code: "ven", name: "Venda" },
  {id: 478, code: "vie", name: "Vietnamese" },
  {id: 479, code: "vol", name: "Volapük" },
  {id: 480, code: "vot", name: "Votic" },
  {id: 481, code: "wak", name: "Wakashan languages" },
  {id: 482, code: "wal", name: "Walamo" },
  {id: 483, code: "war", name: "Waray" },
  {id: 484, code: "was", name: "Washo" },
  {id: 485, code: "wel", name: "Welsh" },
  {id: 486, code: "cym", name: "Welsh" },
  {id: 487, code: "wen", name: "Sorbian languages" },
  {id: 488, code: "wln", name: "Walloon" },
  {id: 489, code: "wol", name: "Wolof" },
  {id: 490, code: "xal", name: "Kalmyk; Oirat" },
  {id: 491, code: "xho", name: "Xhosa" },
  {id: 492, code: "yao", name: "Yao" },
  {id: 493, code: "yap", name: "Yapese" },
  {id: 494, code: "yid", name: "Yiddish" },
  {id: 495, code: "yor", name: "Yoruba" },
  {id: 496, code: "ypk", name: "Yupik languages" },
  {id: 497, code: "zap", name: "Zapotec" },
  {id: 498, code: "zbl", name: "Blissymbols; Blissymbolics; Bliss" },
  {id: 499, code: "zen", name: "Zenaga" },
  {id: 500, code: "zgh", name: "Standard Moroccan Tamazight" },
  {id: 501, code: "zha", name: "Zhuang; Chuang" },
  {id: 502, code: "znd", name: "Zande languages" },
  {id: 503, code: "zul", name: "Zulu" },
  {id: 504, code: "zun", name: "Zuni" },
  {id: 505, code: "zxx", name: "No linguistic content; Not applicable" },
  {id: 506, code: "zza", name: "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" }
]
